HelloKorea/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponse

def hello(request):
    return HttpResponse('''
        <h1>Hello, <a href="http://facebook.com/askdjango/" target="_blank">AskDjango</a></h1>
    ''')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls',namespace='blog')),
    url(r'^$' , hello),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.post_list, name = 'post_list'),
    #문자열 표현하는 정결표현 
    url(r'^(?P<pk>\d+)/$',views.post_detail, name = 'post_detail'),      
]

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    photo = models.ImageField()
    create_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
   #글제목 보기게 함 
    def __str__(self):
        return self.title
    
class Comment(models.Model):
    ##외래키의 역활
    post = models.ForeignKey(Post)
    message = models.TextField()

blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import render
from .models import Post

'''
def post_list(request):
    return render(request, 'blog/post_list.html')
'''    
    
post_list = ListView.as_view(model=Post)

post_detail = DetailView.as_view(model=Post)

blog/templates/blog/base.html
<!doctype html>
<html>
    <head>
        <meta charset = "urf8" />
        <link rel = "stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"/>
        <link rel = "stylesheet" href ="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.6/journal/bootstrap.min.css"/>
        <style>
            body{
                padding-top : 80px;
                padding-bottom : 80px;
                
            }
        </style> 
        
        <body>
            
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">HelloKorea</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    {% block content %}
    {% endblock %}
        </body></head></html>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}

{% block content %}
<div class = "container">
    <div class = "row">
        <div class = "col-sm-12">
            <h1>{{post.title}}></h1>

            <p><img src="{{post.photo.url}}"  /></p>
            {{post.content|linebreaks}}
            
            <hr/>
            <a href ="{%url "blog:post_list" %}"class = "btn btn-primary">목록으로</a>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block content %}
<div class = "container">
    <div class = "row">
        <div class = "col-sm-12">
            <table class ="table table-hover table-bordered">
        {% for post in post_list %}
     <tr>
        <td>
            <a href = "{%url "blog:post_detail" post.pk%}">
            {{post.title}}</td>
            </a>
     </tr>
    {% endfor %}
    </table>
        </div>
    </div>
    
    </div>
    
</ul>
{% endblock %}